{application,exprotobuf,
             [{registered,[]},
              {description,"exprotobuf provides native encoding/decoding of \nprotobuf messages via generated modules/structs.\n"},
              {applications,[kernel,stdlib,elixir]},
              {vsn,"0.8.5"},
              {modules,['Elixir.Protobuf','Elixir.Protobuf.Builder',
                        'Elixir.Protobuf.Config',
                        'Elixir.Protobuf.ConfigError',
                        'Elixir.Protobuf.Decoder',
                        'Elixir.Protobuf.DefineEnum',
                        'Elixir.Protobuf.DefineMessage',
                        'Elixir.Protobuf.Encoder','Elixir.Protobuf.Field',
                        'Elixir.Protobuf.Parser',
                        'Elixir.Protobuf.Parser.ParserError',
                        'Elixir.Protobuf.Utils']}]}.